"""adding crypto currencie

Revision ID: cc257f37dfdd
Revises: f4c52c1efb79
Create Date: 2023-11-29 21:55:16.413483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc257f37dfdd'
down_revision = 'f4c52c1efb79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cryptoImg', sa.String(length=255), nullable=False),
    sa.Column('cryptoName', sa.String(length=50), nullable=False),
    sa.Column('cryptoPrice', sa.String(length=20), nullable=True),
    sa.Column('cryptoSymbol', sa.String(length=10), nullable=False),
    sa.Column('coinIncrement', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cryptoName'),
    sa.UniqueConstraint('cryptoSymbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_currency')
    # ### end Alembic commands ###
