"""new table

Revision ID: efc7931987e4
Revises: 6b9eebb1d091
Create Date: 2023-11-29 22:15:11.876643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc7931987e4'
down_revision = '6b9eebb1d091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cryptoImg', sa.Text(), nullable=False),
    sa.Column('cryptoName', sa.String(length=50), nullable=False),
    sa.Column('cryptoPrice', sa.String(length=20), nullable=True),
    sa.Column('cryptoSymbol', sa.String(length=10), nullable=False),
    sa.Column('coinIncrement', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cryptoName'),
    sa.UniqueConstraint('cryptoSymbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_currency')
    # ### end Alembic commands ###
